############# French navigation ##############
# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Contact"
url = "contact/"
weight = 2



# footer menu
[[footer]]
name = "Changelog"
url = "changelog/"
weight = 1

