############## English navigation ###############
# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Github"
url = "https://github.com/mapgallery/"
weight = 2


# footer menu
[[footer]]
name = "Changelog"
url = "changelog/"
weight = 1

[[footer]]
name = "Contact"
url = "contact/"
weight = 2

[[footer]]
name = "Github"
url = "https://github.com/mapgallery/"
weight = 3